[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
daemonize = "0.5.0"

[dev-dependencies]
tokio = { version = "1.37.0", features = ["full", "test-util"] }